"""
Machine Learning Model Training Script
--------------------------------------
This script trains a Bernoulli Naive Bayes classifier to predict diseases 
based on binary symptom features. 

Model Choice (BernoulliNB):
    We use Bernoulli Naive Bayes because our feature matrix is binary (1/0).
    It is extremely lightweight, memory-efficient, and offers near-instant 
    inference, making it ideal for the limited resources of a MacBook Air M1.
"""

import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report
import joblib
import os
from typing import Optional

# ── Dataset Paths ──────────────────────────────────────────────────────────────
DATASET_PATH    = '../dataset/archive/dataset.csv'
SYNTHETIC_PATH  = '../dataset/archive/synthetic_data.csv'  # Generated by generate_synthetic_data.py
CLINICAL_PATH   = '../dataset/archive/clinical_training_data.csv'  # Curated red-flag & clinical rows
SEVERITY_PATH   = '../dataset/archive/Symptom-severity.csv'
DESCRIPTION_PATH = '../dataset/archive/symptom_Description.csv'
PRECAUTION_PATH  = '../dataset/archive/symptom_precaution.csv'


def normalize_symptom(s: any) -> Optional[str]:
    """Normalizes a symptom string to a standard machine-readable format.

    Args:
        s: The raw symptom string (e.g., " Chest Pain ").

    Returns:
        A lowercased, underscored, and stripped string (e.g., "chest_pain") 
        or None if input is invalid.
    """
    if not isinstance(s, str):
        return None
    return s.lower().strip().replace(" ", "_")


def train_model():
    """Executes the end-to-end Machine Learning training pipeline.

    Steps:
    1. Dataset Merging: Combines the original medical dataset with 
       GXP-synthesized samples for better class balance.
    2. Feature Engineering: Builds a global symptom vocabulary and transforms 
       patient rows into a multi-hot encoded binary matrix.
    3. Classification: Fits a Bernoulli Naive Bayes model.
    4. Serialization: Save the model and all mapping metadata (Specialists, 
       Precautions) into a compressed Joblib bundle for the FastAPI server.
    """
    print("=" * 65)
    print("  🚀 Famplus ML Model Training Pipeline")
    print("=" * 65)

    # ── 1. Load Datasets ───────────────────────────────────────────────────────
    print("\n📂 Loading datasets...")
    df_real = pd.read_csv(DATASET_PATH)
    print(f"   Real data rows       : {len(df_real)}")

    frames = [df_real]

    # Merge synthetic data if it exists (run generate_synthetic_data.py first)
    if os.path.exists(SYNTHETIC_PATH):
        df_synthetic = pd.read_csv(SYNTHETIC_PATH)
        print(f"   Synthetic data rows  : {len(df_synthetic)}")
        frames.append(df_synthetic)
    else:
        print("   ⚠️  Synthetic data not found — training on real data only.")
        print("      Run generate_synthetic_data.py first for better accuracy.")

    # Merge curated clinical data (red-flag / accuracy-focused examples)
    if os.path.exists(CLINICAL_PATH):
        df_clinical = pd.read_csv(CLINICAL_PATH)
        # Normalize column names to match the main dataset schema
        df_clinical.columns = df_clinical.columns.str.strip()
        df_clinical['Disease'] = df_clinical['Disease'].str.strip()
        # Rename Symptom_N columns to match the Symptom_1..Symptom_17 schema
        df_clinical = df_clinical.rename(columns={
            c: c.replace('Symptom_', 'Symptom_')
            for c in df_clinical.columns
        })
        # Align columns — pad missing symptom columns with NaN
        existing_sym_cols = [c for c in df_real.columns if 'Symptom' in c]
        for col in existing_sym_cols:
            if col not in df_clinical.columns:
                df_clinical[col] = None
        df_clinical = df_clinical[['Disease'] + existing_sym_cols]
        # Repeat each clinical row 8× to give it comparable weight to real data
        df_clinical = pd.concat([df_clinical] * 8, ignore_index=True)
        print(f"   Clinical data rows   : {len(df_clinical)} (8x weighted)")
        frames.append(df_clinical)
    else:
        print("   ⚠️  Clinical data not found — skipping curated rows.")

    df = pd.concat(frames, ignore_index=True)
    print(f"   Combined total       : {len(df)} rows")

    # Load supporting CSVs
    severity_df     = pd.read_csv(SEVERITY_PATH)
    description_df  = pd.read_csv(DESCRIPTION_PATH)
    precaution_df   = pd.read_csv(PRECAUTION_PATH)

    # ── 2. Preprocessing ───────────────────────────────────────────────────────
    # Strip whitespace from disease names (original data has trailing spaces on some)
    df['Disease'] = df['Disease'].str.strip()

    # Normalize all symptom columns
    symptom_cols = [c for c in df.columns if 'Symptom' in c]
    for col in symptom_cols:
        df[col] = df[col].apply(normalize_symptom)

    # ── 3. Build Global Symptom Vocabulary ────────────────────────────────────
    all_symptoms: set = set()
    for col in symptom_cols:
        all_symptoms.update(df[col].dropna().unique())
    all_symptoms = sorted(list(all_symptoms))
    print(f"\n📦 Unique symptoms in vocabulary : {len(all_symptoms)}")
    print(f"   Diseases in training set      : {df['Disease'].nunique()}")

    # ── 4. Build Binary Feature Matrix (X) ────────────────────────────────────
    # Shape: (n_samples, n_unique_symptoms)
    # Each cell = 1 if that patient has that symptom, else 0
    print("\n⚙️  Building feature matrix...")
    X = np.zeros((len(df), len(all_symptoms)), dtype=np.float32)
    symptom_to_idx = {s: i for i, s in enumerate(all_symptoms)}

    for i, row in df.iterrows():
        for col in symptom_cols:
            s_val = row[col]
            if s_val in symptom_to_idx:
                X[i, symptom_to_idx[s_val]] = 1.0

    # ── 5. Encode Target Labels ────────────────────────────────────────────────
    # LabelEncoder converts string disease names → integer class indices
    le = LabelEncoder()
    y = le.fit_transform(df['Disease'])
    print(f"   Classes encoded : {len(le.classes_)}")

    # ── 6. Train Upgraded Random Forest ───────────────────────────────────────
    print("\n🧠 Training Bernoulli Naive Bayes Classifier...")

    model = BernoulliNB()
    model.fit(X, y)
    print("✅ Model trained successfully!")

    # ── 7. Cross-Validation Accuracy Report ───────────────────────────────────
    # 5-fold stratified CV ensures each fold has the same class distribution
    print("\n📊 Running 5-fold cross-validation (this may take a moment)...")
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy', n_jobs=-1)
    print(f"   CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
    print(f"   Per-fold   : {[f'{s:.3f}' for s in cv_scores]}")

    # ── 8. Classification Report (per-disease precision, recall, F1) ──────────
    y_pred = model.predict(X)
    print("\n📋 Classification Report (training set):")
    print(classification_report(y, y_pred, target_names=le.classes_, zero_division=0))

    # ── 9. Specialist Map ──────────────────────────────────────────────────────
    # Maps predicted disease → recommended medical specialist
    # This is what the app actually shows to users (the key user-facing output)
    specialist_map = {
        '(vertigo) Paroymsal  Positional Vertigo': 'ENT Specialist',
        'AIDS':                                    'Infectious Disease Specialist',
        'Acne':                                    'Dermatologist',
        'Alcoholic hepatitis':                     'Hepatologist',
        'Allergy':                                 'Allergist',
        'Arthritis':                               'Rheumatologist',
        'Bronchial Asthma':                        'Pulmonologist',
        'Cervical spondylosis':                    'Neurologist',
        'Chicken pox':                             'Infectious Disease Specialist',
        'Chronic cholestasis':                     'Hepatologist',
        'Common Cold':                             'General Physician',
        'Common Flu':                              'General Physician',
        'Dengue':                                  'Infectious Disease Specialist',
        'Diabetes':                                'Endocrinologist',
        'Diabetes ':                               'Endocrinologist',  # handles trailing-space variant
        'Dimorphic hemmorhoids(piles)':            'Gastroenterologist',
        'Drug Reaction':                           'Allergist',
        'Fever':                                   'General Physician',
        'Fungal infection':                        'Dermatologist',
        'GERD':                                    'Gastroenterologist',
        'Gastroenteritis':                         'Gastroenterologist',
        'Heart attack':                            'Cardiologist',
        'Hepatitis B':                             'Hepatologist',
        'Hepatitis C':                             'Hepatologist',
        'Hepatitis D':                             'Hepatologist',
        'Hepatitis E':                             'Hepatologist',
        'Hypertension':                            'Cardiologist',
        'Hypertension ':                           'Cardiologist',     # trailing-space variant
        'Hyperthyroidism':                         'Endocrinologist',
        'Hypoglycemia':                            'Endocrinologist',
        'Hypothyroidism':                          'Endocrinologist',
        'Impetigo':                                'Dermatologist',
        'Insomnia':                                'Sleep Specialist',
        'Jaundice':                                'Hepatologist',
        'Malaria':                                 'Infectious Disease Specialist',
        'Migraine':                                'Neurologist',
        'Osteoarthristis':                         'Rheumatologist',
        'Paralysis (brain hemorrhage)':            'Neurologist',
        'Peptic ulcer diseae':                     'Gastroenterologist',
        'Pneumonia':                               'Pulmonologist',
        'Psoriasis':                               'Dermatologist',
        'Slight Headache':                         'General Physician',
        'Stomach ache':                            'Gastroenterologist',
        'Tuberculosis':                            'Pulmonologist',
        'Typhoid':                                 'Infectious Disease Specialist',
        'Urinary tract infection':                 'Urologist',
        'Varicose veins':                          'Vascular Surgeon',
        'hepatitis A':                             'Hepatologist',
    }

    # ── 10. Severity Map ───────────────────────────────────────────────────────
    # Used to detect clinical urgency based on which symptoms are present
    severity_map = dict(zip(
        severity_df['Symptom'].apply(normalize_symptom),
        severity_df['weight']
    ))

    # ── 11. Description Map ────────────────────────────────────────────────────
    # Human-readable explanation of each condition shown on the result screen
    description_map = dict(zip(
        description_df['Disease'].str.strip(),
        description_df['Description']
    ))

    # ── 12. Precaution Map ─────────────────────────────────────────────────────
    # Actionable steps displayed per-disease to the user
    precaution_map = {}
    for _, row in precaution_df.iterrows():
        disease = row['Disease'].strip()
        precautions = [
            row[c].capitalize() for c in precaution_df.columns
            if 'Precaution' in c and pd.notna(row[c])
        ]
        precaution_map[disease] = precautions

    # ── 13. Bundle & Save Metadata ─────────────────────────────────────────────
    # All metadata is saved alongside the model so the inference server is
    # fully self-contained and does not need the original CSVs at runtime.
    metadata = {
        'all_symptoms':    all_symptoms,     # Feature vector column order
        'label_encoder':   le,               # int → disease name decoder
        'specialist_map':  specialist_map,   # disease → doctor type
        'severity_map':    severity_map,     # symptom → urgency weight
        'description_map': description_map,  # disease → explanation text
        'precaution_map':  precaution_map,   # disease → action steps list
    }

    joblib.dump(model, 'model.joblib', compress=3)
    joblib.dump(metadata, 'metadata.joblib', compress=3)

    print("\n" + "=" * 65)
    print("💾 model.joblib and metadata.joblib saved.")
    print(f"   Total training rows : {len(df)}")
    print(f"   CV Accuracy         : {cv_scores.mean():.2%}")
    print("=" * 65)


if __name__ == "__main__":
    train_model()
