"""
Machine Learning Model Training Script (v2 — Vitals-Aware Gradient Boosting)
------------------------------------------------------------------------------
This script trains a Histogram-based Gradient Boosted Decision Tree classifier 
to predict diseases based on binary symptom features AND numerical vitals.

Model Choice (HistGradientBoostingClassifier):
    scikit-learn's HistGradientBoostingClassifier is a production-grade gradient 
    boosting implementation inspired by LightGBM. It offers:
        - Dramatically better accuracy than Naive Bayes
        - Native handling of mixed feature types (binary symptoms + numerical vitals)
        - Histogram binning for memory efficiency (~300MB RAM during training)
        - Zero extra dependencies (built into scikit-learn)
        - Full Apple Silicon (M1/M2) compatibility out of the box

v2 Enhancement (Vitals-Aware):
    The feature vector now includes 4 numerical vitals columns alongside the 
    binary symptom columns:
        - Age         (years)
        - HeartRate   (bpm)
        - SystolicBP  (mmHg)
        - DiastolicBP (mmHg)
    
    This allows the model to learn age-specific and vitals-correlated patterns:
    e.g., chest pain + age 60 + high BP → Heart Attack (high confidence)
    vs.   chest pain + age 20 + normal BP → Anxiety/GERD (lower cardiac risk)
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report
import joblib
import os
from typing import Optional

# ── Dataset Paths ──────────────────────────────────────────────────────────────
DATASET_PATH    = '../dataset/archive/dataset.csv'
SYNTHETIC_PATH  = '../dataset/archive/synthetic_data.csv'  # Generated by generate_synthetic_data.py
CLINICAL_PATH   = '../dataset/archive/clinical_training_data.csv'  # Curated red-flag & clinical rows
SEVERITY_PATH   = '../dataset/archive/Symptom-severity.csv'
DESCRIPTION_PATH = '../dataset/archive/symptom_Description.csv'
PRECAUTION_PATH  = '../dataset/archive/symptom_precaution.csv'


def normalize_symptom(s: any) -> Optional[str]:
    """Normalizes a symptom string to a standard machine-readable format.

    Args:
        s: The raw symptom string (e.g., " Chest Pain ").

    Returns:
        A lowercased, underscored, and stripped string (e.g., "chest_pain") 
        or None if input is invalid.
    """
    if not isinstance(s, str):
        return None
    return s.lower().strip().replace(" ", "_")


def train_model():
    """Executes the end-to-end Machine Learning training pipeline.

    Steps:
    1. Dataset Merging: Combines the original medical dataset with 
       GXP-synthesized samples for better class balance.
    2. Feature Engineering: Builds a global symptom vocabulary and transforms 
       patient rows into a combined binary (symptoms) + numerical (vitals) matrix.
    3. Classification: Fits a HistGradientBoosting model.
    4. Serialization: Save the model and all mapping metadata (Specialists, 
       Precautions, Scaler) into a compressed Joblib bundle for the FastAPI server.
    """
    print("=" * 65)
    print("  🚀 Famplus ML Model Training Pipeline (v2 — Gradient Boosting)")
    print("=" * 65)

    # ── 1. Load Datasets ───────────────────────────────────────────────────────
    print("\n📂 Loading datasets...")
    df_real = pd.read_csv(DATASET_PATH)
    print(f"   Real data rows       : {len(df_real)}")

    frames = [df_real]

    # Merge synthetic data if it exists (run generate_synthetic_data.py first)
    has_vitals_in_synthetic = False
    if os.path.exists(SYNTHETIC_PATH):
        df_synthetic = pd.read_csv(SYNTHETIC_PATH)
        print(f"   Synthetic data rows  : {len(df_synthetic)}")
        # Check if synthetic data has vitals columns
        if 'Age' in df_synthetic.columns:
            has_vitals_in_synthetic = True
            print(f"   ✅ Synthetic data includes vitals (Age, HeartRate, SystolicBP, DiastolicBP)")
        frames.append(df_synthetic)
    else:
        print("   ⚠️  Synthetic data not found — training on real data only.")
        print("      Run generate_synthetic_data.py first for better accuracy.")

    # Merge curated clinical data (red-flag / accuracy-focused examples)
    if os.path.exists(CLINICAL_PATH):
        df_clinical = pd.read_csv(CLINICAL_PATH)
        # Normalize column names to match the main dataset schema
        df_clinical.columns = df_clinical.columns.str.strip()
        df_clinical['Disease'] = df_clinical['Disease'].str.strip()
        # Rename Symptom_N columns to match the Symptom_1..Symptom_17 schema
        df_clinical = df_clinical.rename(columns={
            c: c.replace('Symptom_', 'Symptom_')
            for c in df_clinical.columns
        })
        # Align columns — pad missing symptom columns with NaN
        existing_sym_cols = [c for c in df_real.columns if 'Symptom' in c]
        for col in existing_sym_cols:
            if col not in df_clinical.columns:
                df_clinical[col] = None
        # Keep Disease + symptom cols (vitals will be filled with defaults)
        keep_cols = ['Disease'] + existing_sym_cols
        # Add vitals if present
        for vc in ['Age', 'HeartRate', 'SystolicBP', 'DiastolicBP']:
            if vc in df_clinical.columns:
                keep_cols.append(vc)
        df_clinical = df_clinical[[c for c in keep_cols if c in df_clinical.columns]]
        # Repeat each clinical row 15× to give red-flag conditions strong weight
        # (increased from 8× to improve emergency condition detection accuracy)
        df_clinical = pd.concat([df_clinical] * 15, ignore_index=True)
        print(f"   Clinical data rows   : {len(df_clinical)} (15x weighted)")
        frames.append(df_clinical)
    else:
        print("   ⚠️  Clinical data not found — skipping curated rows.")

    df = pd.concat(frames, ignore_index=True)
    print(f"   Combined total       : {len(df)} rows")

    # Load supporting CSVs
    severity_df     = pd.read_csv(SEVERITY_PATH)
    description_df  = pd.read_csv(DESCRIPTION_PATH)
    precaution_df   = pd.read_csv(PRECAUTION_PATH)

    # ── 2. Preprocessing ───────────────────────────────────────────────────────
    # Strip whitespace from disease names (original data has trailing spaces on some)
    df['Disease'] = df['Disease'].str.strip()

    # Normalize all symptom columns
    symptom_cols = [c for c in df.columns if 'Symptom' in c]
    for col in symptom_cols:
        df[col] = df[col].apply(normalize_symptom)

    # ── 3. Build Global Symptom Vocabulary ────────────────────────────────────
    all_symptoms: set = set()
    for col in symptom_cols:
        all_symptoms.update(df[col].dropna().unique())
    all_symptoms = sorted(list(all_symptoms))
    print(f"\n📦 Unique symptoms in vocabulary : {len(all_symptoms)}")
    print(f"   Diseases in training set      : {df['Disease'].nunique()}")

    # ── 4. Build Combined Feature Matrix (X) ──────────────────────────────────
    # Shape: (n_samples, n_unique_symptoms + 4_vitals)
    # Symptoms = binary (0/1), Vitals = numerical (scaled later)
    n_symptom_features = len(all_symptoms)
    n_vitals_features  = 4  # Age, HeartRate, SystolicBP, DiastolicBP
    n_total_features   = n_symptom_features + n_vitals_features

    print(f"\n⚙️  Building feature matrix...")
    print(f"   Symptom features : {n_symptom_features}")
    print(f"   Vitals features  : {n_vitals_features} (Age, HeartRate, SystolicBP, DiastolicBP)")
    print(f"   Total features   : {n_total_features}")

    X = np.zeros((len(df), n_total_features), dtype=np.float32)
    symptom_to_idx = {s: i for i, s in enumerate(all_symptoms)}

    # Fill symptom columns (binary)
    for i, row in df.iterrows():
        for col in symptom_cols:
            s_val = row[col]
            if s_val in symptom_to_idx:
                X[i, symptom_to_idx[s_val]] = 1.0

    # Fill vitals columns (numerical)
    vitals_col_names = ['Age', 'HeartRate', 'SystolicBP', 'DiastolicBP']
    vitals_defaults  = [35, 75, 120, 78]  # Population mean defaults

    for j, (vcol, default) in enumerate(zip(vitals_col_names, vitals_defaults)):
        col_idx = n_symptom_features + j
        if vcol in df.columns:
            X[:, col_idx] = df[vcol].fillna(default).values.astype(np.float32)
        else:
            X[:, col_idx] = default  # Fill with default if column missing

    # ── 4b. Scale Vitals Features ─────────────────────────────────────────────
    # StandardScaler normalizes vitals to zero-mean unit-variance.
    # This helps the gradient boosting model properly weight vitals alongside binary symptoms.
    vitals_scaler = StandardScaler()
    vitals_slice  = X[:, n_symptom_features:]    # Last 4 columns
    X[:, n_symptom_features:] = vitals_scaler.fit_transform(vitals_slice)

    print(f"   Vitals scaled (mean → 0, std → 1)")
    for j, vcol in enumerate(vitals_col_names):
        print(f"     {vcol}: mean={vitals_scaler.mean_[j]:.1f}, std={vitals_scaler.scale_[j]:.1f}")

    # ── 5. Encode Target Labels ────────────────────────────────────────────────
    # LabelEncoder converts string disease names → integer class indices
    le = LabelEncoder()
    y = le.fit_transform(df['Disease'])
    n_classes = len(le.classes_)
    print(f"   Classes encoded : {n_classes}")

    # ── 6. Train HistGradientBoosting Classifier ──────────────────────────────
    print("\n🧠 Training HistGradientBoosting Classifier...")
    print("   (scikit-learn's built-in gradient boosting — significantly more powerful than Naive Bayes)")

    model = HistGradientBoostingClassifier(
        # ── Tree Architecture ──────────────────────────────────────────────
        max_iter=300,               # Number of boosting iterations (trees)
        max_depth=6,                # Max depth per tree (prevents overfitting)
        min_samples_leaf=5,         # Minimum samples per leaf

        # ── Learning ────────────────────────────────────────────────────────
        learning_rate=0.1,          # Step size shrinkage (lower = more conservative)

        # ── Regularization ──────────────────────────────────────────────────
        l2_regularization=1.0,      # L2 regularization (weight decay)

        # ── System ──────────────────────────────────────────────────────────
        random_state=42,
        verbose=0,
        max_bins=255,               # Histogram bins for memory efficiency
    )

    model.fit(X, y)
    print("✅ Model trained successfully!")

    # ── 7. Cross-Validation Accuracy Report ───────────────────────────────────
    # 5-fold stratified CV ensures each fold has the same class distribution
    print("\n📊 Running 5-fold cross-validation (this may take a moment)...")
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model, X, y, cv=cv, scoring='accuracy', n_jobs=-1)
    print(f"   CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
    print(f"   Per-fold   : {[f'{s:.3f}' for s in cv_scores]}")

    # ── 8. Classification Report (per-disease precision, recall, F1) ──────────
    y_pred = model.predict(X)
    print("\n📋 Classification Report (training set):")
    print(classification_report(y, y_pred, target_names=le.classes_, zero_division=0))

    # ── 9. Specialist Map ──────────────────────────────────────────────────────
    # Maps predicted disease → recommended medical specialist
    # This is what the app actually shows to users (the key user-facing output)
    specialist_map = {
        '(vertigo) Paroymsal  Positional Vertigo': 'ENT Specialist',
        'AIDS':                                    'Infectious Disease Specialist',
        'Acne':                                    'Dermatologist',
        'Alcoholic hepatitis':                     'Hepatologist',
        'Allergy':                                 'Allergist',
        'Arthritis':                               'Rheumatologist',
        'Bronchial Asthma':                        'Pulmonologist',
        'Cervical spondylosis':                    'Neurologist',
        'Chicken pox':                             'Infectious Disease Specialist',
        'Chronic cholestasis':                     'Hepatologist',
        'Common Cold':                             'General Physician',
        'Common Flu':                              'General Physician',
        'Dengue':                                  'Infectious Disease Specialist',
        'Diabetes':                                'Endocrinologist',
        'Diabetes ':                               'Endocrinologist',  # handles trailing-space variant
        'Dimorphic hemmorhoids(piles)':            'Gastroenterologist',
        'Drug Reaction':                           'Allergist',
        'Fever':                                   'General Physician',
        'Fungal infection':                        'Dermatologist',
        'GERD':                                    'Gastroenterologist',
        'Gastroenteritis':                         'Gastroenterologist',
        'Heart attack':                            'Cardiologist',
        'Hepatitis B':                             'Hepatologist',
        'Hepatitis C':                             'Hepatologist',
        'Hepatitis D':                             'Hepatologist',
        'Hepatitis E':                             'Hepatologist',
        'Hypertension':                            'Cardiologist',
        'Hypertension ':                           'Cardiologist',     # trailing-space variant
        'Hyperthyroidism':                         'Endocrinologist',
        'Hypoglycemia':                            'Endocrinologist',
        'Hypothyroidism':                          'Endocrinologist',
        'Impetigo':                                'Dermatologist',
        'Insomnia':                                'Sleep Specialist',
        'Jaundice':                                'Hepatologist',
        'Malaria':                                 'Infectious Disease Specialist',
        'Migraine':                                'Neurologist',
        'Osteoarthristis':                         'Rheumatologist',
        'Paralysis (brain hemorrhage)':            'Neurologist',
        'Peptic ulcer diseae':                     'Gastroenterologist',
        'Pneumonia':                               'Pulmonologist',
        'Psoriasis':                               'Dermatologist',
        'Slight Headache':                         'General Physician',
        'Stomach ache':                            'Gastroenterologist',
        'Tuberculosis':                            'Pulmonologist',
        'Typhoid':                                 'Infectious Disease Specialist',
        'Urinary tract infection':                 'Urologist',
        'Varicose veins':                          'Vascular Surgeon',
        'hepatitis A':                             'Hepatologist',
    }

    # ── 10. Severity Map ───────────────────────────────────────────────────────
    # Used to detect clinical urgency based on which symptoms are present
    severity_map = dict(zip(
        severity_df['Symptom'].apply(normalize_symptom),
        severity_df['weight']
    ))

    # ── 11. Description Map ────────────────────────────────────────────────────
    # Human-readable explanation of each condition shown on the result screen
    description_map = dict(zip(
        description_df['Disease'].str.strip(),
        description_df['Description']
    ))

    # ── 12. Precaution Map ─────────────────────────────────────────────────────
    # Actionable steps displayed per-disease to the user
    precaution_map = {}
    for _, row in precaution_df.iterrows():
        disease = row['Disease'].strip()
        precautions = [
            row[c].capitalize() for c in precaution_df.columns
            if 'Precaution' in c and pd.notna(row[c])
        ]
        precaution_map[disease] = precautions

    # ── 13. Bundle & Save Metadata ─────────────────────────────────────────────
    # All metadata is saved alongside the model so the inference server is
    # fully self-contained and does not need the original CSVs at runtime.
    metadata = {
        'all_symptoms':    all_symptoms,       # Feature vector column order
        'label_encoder':   le,                 # int → disease name decoder
        'specialist_map':  specialist_map,     # disease → doctor type
        'severity_map':    severity_map,       # symptom → urgency weight
        'description_map': description_map,    # disease → explanation text
        'precaution_map':  precaution_map,     # disease → action steps list
        'vitals_scaler':   vitals_scaler,      # StandardScaler for vitals normalization
        'vitals_columns':  vitals_col_names,   # ['Age', 'HeartRate', 'SystolicBP', 'DiastolicBP']
        'model_type':      'gradient_boosting', # Flag for the inference engine
    }

    joblib.dump(model, 'model.joblib', compress=3)
    joblib.dump(metadata, 'metadata.joblib', compress=3)

    model_size_mb = os.path.getsize('model.joblib') / (1024 * 1024)
    meta_size_mb  = os.path.getsize('metadata.joblib') / (1024 * 1024)

    print("\n" + "=" * 65)
    print("💾 model.joblib and metadata.joblib saved.")
    print(f"   Model architecture  : HistGradientBoosting ({model.max_iter} iterations, depth {model.max_depth})")
    print(f"   Total features      : {n_total_features} ({n_symptom_features} symptoms + {n_vitals_features} vitals)")
    print(f"   Total training rows : {len(df)}")
    print(f"   CV Accuracy         : {cv_scores.mean():.2%}")
    print(f"   Model file size     : {model_size_mb:.1f} MB")
    print(f"   Metadata file size  : {meta_size_mb:.1f} MB")
    print("=" * 65)


if __name__ == "__main__":
    train_model()
