/**
 * @file badge.tsx
 * @description Provides a reusable Badge UI component.
 * Features built-in variations for different semantical states (e.g. destructive, secondary).
 * Styled using Tailwind CSS via the `class-variance-authority` (cva) utility.
 */

import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "@radix-ui/react-slot"

import { cn } from "@/lib/utils"

/**
 * Tailwind styling generator for Badge components.
 * Contains base styles shared by all badges, and specific thematic modifiers.
 */
const badgeVariants = cva(
  // Fundamental badge styling: sizing, flex alignment, transitions, font settings
  "inline-flex items-center justify-center rounded-full border border-transparent px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 [&>svg]:size-3 gap-1 [&>svg]:pointer-events-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive transition-[color,box-shadow] overflow-hidden",
  {
    variants: {
      variant: {
        // Theme-specific background and text color assignments
        default: "bg-primary text-primary-foreground [a&]:hover:bg-primary/90",
        secondary:
          "bg-secondary text-secondary-foreground [a&]:hover:bg-secondary/90",
        destructive:
          "bg-destructive text-white [a&]:hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border-border text-foreground [a&]:hover:bg-accent [a&]:hover:text-accent-foreground",
        ghost: "[a&]:hover:bg-accent [a&]:hover:text-accent-foreground",
        link: "text-primary underline-offset-4 [a&]:hover:underline",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

/**
 * Props definition for the Badge Component.
 * - Extracts native span attributes
 * - Inherits types generated by CVA for standard component variations
 * - Provides `asChild` capability from Radix to merge props onto a custom element
 */
export interface BadgeProps
  extends React.HTMLAttributes<HTMLSpanElement>,
    VariantProps<typeof badgeVariants> {
  asChild?: boolean
}

/**
 * Universal Badge visual element.
 * @param {BadgeProps} props React props
 * @returns {JSX.Element} Fully styled interface Badge.
 */
function Badge({
  className,
  variant = "default",
  asChild = false,
  ...props
}: BadgeProps) {
  // If asChild is true, we render a Radix Slot to combine with child components
  // Otherwise, we default to a standard <span> tag.
  const Comp = asChild ? Slot : "span"

  return (
    // @ts-ignore
    <Comp
      data-slot="badge"
      data-variant={variant}
      // cn(...) cleanly merges any custom classNames with the internally generated cva classes
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  )
}

export { Badge, badgeVariants }
